services:
  backend:
    build:
      context: ./backend
    container_name: backend-telemetria
    environment:
      PORT: 8080
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8080:8080"
    cpus: "${BACKEND_CPUS:-0.50}"
    mem_limit: "${BACKEND_MEM:-256m}"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  consumer:
    build:
      context: ./consumer
    container_name: consumidor-telemetria
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/telemetria?sslmode=disable
    cpus: "${CONSUMER_CPUS:-0.50}"
    mem_limit: "${CONSUMER_MEM:-256m}"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: fila-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    cpus: "${RABBITMQ_CPUS:-0.50}"
    mem_limit: "${RABBITMQ_MEM:-512m}"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: banco-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telemetria
    ports:
      - "5432:5432"
    cpus: "${POSTGRES_CPUS:-0.50}"
    mem_limit: "${POSTGRES_MEM:-512m}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d telemetria"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
